// SwiftLint configuration for production-ready code
// Garante código limpo, consistente e de alta qualidade

disabled_rules:
  - trailing_whitespace
  - todo

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_xctest_method
  - explicit_self
  - fatal_error_message
  - file_name
  - file_name_no_space
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

included:
  - App.swift
  - ContentView.swift
  - AuthenticationView.swift
  - Models.swift
  - SupabaseClient.swift
  - Tests.swift

excluded:
  - Pods
  - archive
  - build
  - .build
  - node_modules

# Rules Configuration

line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 2
  max_length: 50

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - db

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

large_tuple:
  warning: 3
  error: 4

# Custom Rules

custom_rules:
  force_https:
    name: "Force HTTPS"
    regex: "(http://)"
    message: "Use HTTPS em vez de HTTP"
    severity: error
    
  no_print_in_production:
    name: "No print() in production"
    regex: "^\\s*print\\("
    message: "Use logging adequado em vez de print()"
    severity: warning
    excluded: ".*Tests\\.swift"
    
  double_space:
    name: "Double space"
    regex: "([a-z,A-Z] \\s+)"
    message: "Remova espaços duplos"
    severity: warning
    
  empty_commented_line:
    name: "Empty commented line"
    regex: "^\\s*//\\s*$"
    message: "Remova comentários vazios"
    severity: warning
    
  mark_comment:
    name: "Mark comment"
    regex: "// MARK:"
    message: "Use '// MARK: -' com hífen"
    severity: warning
    
  unnecessary_type:
    name: "Unnecessary type"
    regex: "[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[ ]?=[ ]?\\1"
    message: "Tipo é desnecessário"
    severity: warning

reporter: "xcode"
