name: Android production build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    type: submit
    needs: [build_android]
    params:
      build_id: ${{ needs.build_android.outputs.build_id }}
