name: Android production build

on:
  push:
    branches:
      - release

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production

  submit_android:
    type: submit
    needs: [build_android]
    params:
      platform: android
      profile: production
