name: iOS production build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    type: submit
    needs: [build_ios]
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
