name: iOS production build

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    type: submit
    needs: [build_ios]
    params:
      platform: ios
      profile: production
